#!/usr/bin/env bash
# Display information about subdomains

display_info () {
    dig "$2.$1" | awk '/ANSWER SECTION:/ { getline ; print "The subdomain '$2' is a " $4 " record and points to " $5 }'
    return 0
}

if [ $# -eq 1 ]
then
    display_info "$1" "www"
    display_info "$1" "lb-01"
    display_info "$1" "web-01"
    display_info "$1" "web-02"
else
    display_info "$1" "$2"
fi
