#!/usr/bin/env bash
# Installs nginx web server and creates an index.html

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html
sudo bash -c 'echo "Holberton School" > /var/www/html/index.html'
sudo serivice nginx restart
