#!/user/bin/env bash
# Configures an nginx server with a custom http response header

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "11i add_header X-Served-By \$hostname;" /etc/nginx/nginx.conf
sudo service nginx restart
