#!/usr/bin/env bash
# Prints Holberton Shool ten times. The 9th time is followed by Hi

i=0
while [ $i -lt 10 ]
do
    echo "Holberton School"
    if [ $i -eq 8 ]
    then
        echo "Hi"
    fi
    let i+=1
done
