#!/usr/bin/env bash
# Prints all minutes and hour in the day

hour=0
while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    minutes=1
    while [ $minutes -lt 60 ]
    do
        echo $minutes
        let minutes+=1
    done
    let hour+=1
done
