#!/usr/bin/env bash
# Run nginx as user nginx and listen on port 8080
sudo sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo pkill apache2
sudo chmod 777 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
